version: '3'

networks:
  app:

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  php:
    build: ./app
    working_dir: /var/www
    volumes:
      - ./app:/var/www/app
      - ./data:/var/www/app/data
    networks:
      - app
    env_file:
      - .env
  
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    networks:
      - app
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root